#use_frameworks!
#inhibit_all_warnings!
#platform:ios,"10.0"
#source 'https://github.com/CocoaPods/Specs.git'
#
#target 'TJAudioPlay_Example' do
#    pod 'TJAudioPlay' ,'0.2.0'
#end


use_frameworks!
inhibit_all_warnings!
platform:ios,"10.0"
source 'https://github.com/CocoaPods/Specs.git'

target 'TJAudioPlay_Example' do
  pod 'TJAudioPlay', :path => '../'
end

target 'TJAudioPlay_Tests' do
    inherit! :search_paths
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 10.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
  end
end
